---
app_name: acme-order-hub
app_user: acme
app_install_dir: /opt/acme
app_root: "{{ app_install_dir }}/lightwell_app"
app_jar_dest: "{{ app_install_dir }}/acme-order-hub.jar"
app_port: 8080

lightwell_app_repo: "https://github.com/ansible-tmm/lightwell_app.git"
lightwell_app_version: main

deploy_from_git: true
maven_profile: community
maven_settings_file: "{{ app_root }}/maven/settings-mock.xml"
build_mock_lightwell_repo: false
use_real_lightwell: false
fetch_artifact_to_controller: false
controller_artifacts_dir: "{{ playbook_dir }}/../artifacts"

jar_source: controller
