spring.application.name=acme-order-hub
server.port=8080

lightwell.build.profile=@lightwell.build.profile@
lightwell.spring-framework.version=@spring-framework.version@
lightwell.jackson.version=@jackson.version@
lightwell.commons-text.version=@commons-text.version@
